# Generated by Django 6.1 on 2026-08-11 11:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimberAscent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('climber_name', models.CharField(default='Anonimowy Wspinacz', max_length=100, verbose_name='Wspinacz')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Ocena jakości 1-5 gwiazdek')),
                ('perceived_grade', models.CharField(help_text='Grade zdaniem wspinacza', max_length=10)),
                ('comment', models.TextField(blank=True, verbose_name='Komentarz / Feedback dla settera')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data przejścia')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ascents', to='routes.route', verbose_name='Droga')),
            ],
            options={
                'verbose_name': 'Przejście i Ocena Drogi',
                'verbose_name_plural': 'Przejścia i Analityka Popularności',
                'ordering': ['-created_at'],
            },
        ),
    ]
