# Generated by Django 6.1 on 2026-08-11 11:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Nazwa sektora')),
                ('sector_type', models.CharField(choices=[('bouldering', 'Bouldering'), ('rope_wall', 'Ściana Linowa'), ('training', 'Strefa Treningowa')], default='bouldering', max_length=20, verbose_name='Typ sektora')),
                ('max_capacity', models.PositiveIntegerField(default=20, help_text='Maksymalna optymalna pojemność dróg/baldów')),
                ('color_code', models.CharField(default='#3b82f6', help_text='Kod HEX koloru oznaczającego sektor', max_length=7)),
                ('target_rotation_days', models.PositiveIntegerField(default=45, help_text='Docelowy okres rotacji sektora w dniach')),
                ('last_reset_date', models.DateField(blank=True, null=True, verbose_name='Ostatni reset')),
                ('next_scheduled_reset', models.DateField(blank=True, null=True, verbose_name='Zaplanowany reset')),
            ],
            options={
                'verbose_name': 'Sektor',
                'verbose_name_plural': 'Sektory',
                'ordering': ['name'],
            },
        ),
    ]
