# Generated by Django 6.1 on 2026-08-22 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_gym'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='gyms.gym'),
        ),
    ]
