# Generated by Django 6.1 on 2026-08-22 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_sector_gym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='gyms.gym'),
        ),
    ]
