# Generated by Django 6.1 on 2026-08-11 11:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Nazwa / Tytuł drogi')),
                ('route_type', models.CharField(choices=[('boulder', 'Boulder'), ('rope', 'Lina')], default='boulder', max_length=10, verbose_name='Typ')),
                ('grade', models.CharField(help_text='Wycena francuska np. 6A, 7B+', max_length=10)),
                ('v_grade', models.CharField(blank=True, help_text='Wycena V-Grade np. V3, V7', max_length=10, null=True)),
                ('wall_line_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numer linii / stanowiska')),
                ('hold_color', models.CharField(max_length=30, verbose_name='Kolor chwytów')),
                ('setter_name', models.CharField(default='Główny Setter', max_length=100, verbose_name='Autor / Setter')),
                ('date_set', models.DateField(default=django.utils.timezone.now, verbose_name='Data nakręcenia')),
                ('status', models.CharField(choices=[('active', 'Aktywna'), ('deprecated', 'Zdemontowana')], default='active', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Opis i charakterystyka')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='Kod QR')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='gyms.sector', verbose_name='Sektor')),
            ],
            options={
                'verbose_name': 'Droga / Boulder',
                'verbose_name_plural': 'Baza Dróg i Baldów',
                'ordering': ['-date_set'],
            },
        ),
    ]
