# Generated by Django 5.2.17 on 2026-08-25 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
        ('setting', '0004_alter_settertask_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='setter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='setting.setterprofile'),
        ),
    ]
