# Generated by Django 5.2.17 on 2026-08-25 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_route_setter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='date_set',
            field=models.DateField(default=datetime.date.today, verbose_name='Data nakręcenia'),
        ),
    ]
