# Generated by Django 6.1 on 2026-08-21 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('gyms', '0002_gym'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='gyms.gym'),
        ),
    ]
