# Generated by Django 6.1 on 2026-08-11 11:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetHistoryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Data resetu')),
                ('sector_name', models.CharField(max_length=120, verbose_name='Sektor')),
                ('lead_setter_name', models.CharField(max_length=120, verbose_name='Szef resetu')),
                ('routes_stripped', models.PositiveIntegerField(verbose_name='Odkręcone drogi')),
                ('routes_set', models.PositiveIntegerField(verbose_name='Nakręcone nowe drogi')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki i uwagi')),
            ],
            options={
                'verbose_name': 'Log Resetu',
                'verbose_name_plural': 'Historia Wymian Dróg',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SetterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Head Route Setter', max_length=50)),
                ('specialties', models.CharField(help_text='np. Dachy, Połogi, Dyno', max_length=255)),
                ('avatar_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setter_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SettingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Tytuł sesji resetowej')),
                ('scheduled_date', models.DateField(verbose_name='Planowana data')),
                ('status', models.CharField(choices=[('planned', 'Zaplanowana'), ('in_progress', 'W trakcie'), ('completed', 'Zakończona')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Wskazówki i koncepcja')),
                ('lead_setter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_sessions', to='setting.setterprofile')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting_sessions', to='gyms.sector')),
            ],
        ),
        migrations.CreateModel(
            name='SetterTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120, verbose_name='Zadanie / Prototyp')),
                ('target_grade', models.CharField(max_length=10, verbose_name='Docelowa wycena')),
                ('hold_color', models.CharField(max_length=20, verbose_name='Kolor chwytów')),
                ('sector_name', models.CharField(default='Sektor Główny', max_length=100)),
                ('status', models.CharField(choices=[('todo', 'Do kręcenia'), ('in_progress', 'W trakcie'), ('testing', 'Forsovanie / Testy'), ('done', 'Gotowe')], default='todo', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Termin wykonania')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Data utworzenia')),
                ('setter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='setting.setterprofile')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='setting.settingsession')),
            ],
        ),
    ]
