# Generated by Django 5.2.17 on 2026-08-23 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_resethistorylog_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resethistorylog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reset_history_logs', to='setting.settingsession'),
        ),
        migrations.AlterField(
            model_name='settertask',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='setting.settingsession'),
        ),
    ]
