# Generated by Django 6.1 on 2026-08-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_alter_resethistorylog_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settertask',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
    ]
