# Generated by Django 5.2.17 on 2026-08-27 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_sector_gym'),
        ('setting', '0004_alter_settertask_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='settertask',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='setter_tasks', to='gyms.sector'),
        ),
    ]
