# Generated by Django 5.2.17 on 2026-08-27 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_alter_route_date_set'),
        ('setting', '0005_settertask_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='settertask',
            name='created_route',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_task', to='routes.route'),
        ),
    ]
