# Generated by Django 5.2.17 on 2026-08-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_settertask_created_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='settertask',
            name='route_type',
            field=models.CharField(choices=[('boulder', 'Boulder'), ('rope', 'Rope')], default='boulder', max_length=20),
        ),
    ]
