# Generated by Django 5.2.17 on 2026-08-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0007_settertask_route_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsession',
            name='target_grade_breakdown',
            field=models.JSONField(blank=True, default=dict, verbose_name='Planowany rozkład wycen'),
        ),
        migrations.AddField(
            model_name='settingsession',
            name='target_route_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Docelowa liczba dróg'),
        ),
    ]
